CREATE DATABASE eternal;
USE eternal;
CREATE TABLE TET (
	number INT(3) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR (32),
	rarity CHAR(1),
	cost VARCHAR(2),
	faction VARCHAR(2),
	infreq CHAR(2),
	card_type VARCHAR(10),
	RNG TINYINT(2) UNSIGNED) ENGINE MyISAM;
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Granite Monument', 'U', 'N', 'F', 'F', 'power', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Charchain Flail', 'R', '0', 'F', 'FF', 'attachment', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Flame Blast', 'U', '0', 'F', 'FFF', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Trail Stories', 'R', '0', 'F', 'F', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Frontier Jito', 'R', '1', 'F', 'F', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Grenadin Drone', 'C', '1', 'F', 'F', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hevy Axe', 'C', '1', 'F', 'F', 'attachment', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Light the Fuse', 'L', '1', 'F', 'F', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Oni Roning', 'C', '1', 'F', 'F', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Pyroknight', 'R', '1', 'F', 'F', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ruin', 'C', '1', 'F', 'F', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ruthless Stranger', 'U', '1', 'F', 'F', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Temper', 'C', '1', 'F', 'F', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ticking Genadin', 'C', '1', 'F', 'F', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Torch', 'C', '1', 'F', 'F', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Warhelm', 'U', '1', 'F', 'F', 'attachment', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Bladekin Apprentice', 'U', '2', 'F', 'F', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Brazen Daredevil', 'R', '2', 'F', 'F', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ornate Katana', 'C', '2', 'F', 'F', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Piercing Shot', 'U', '2', 'F', 'F', 'spell', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Pyre Adept', 'C', '2', 'F', 'F', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rakano Outlaw', 'U', '2', 'F', 'F', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rampage', 'C', '2', 'F', 'F', 'spell', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Song of War', 'R', '2', 'F', 'F', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Assembly Line', 'U', '3', 'F', 'F', 'spell', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Censari Brigand', 'R', '3', 'F', 'FF', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Granite Acolyte', 'C', '3', 'F', 'F', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Oni Quartermaster', 'U', '3', 'F', 'F', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rakano Flagbearer', 'U', '3', 'F', 'F', 'unit', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rally', 'C', '3', 'F', 'F', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rebel Sharpshooter', 'C', '3', 'F', 'F', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Shogun’s Scepter', 'R', '3', 'F', 'FF', 'attachment', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Burn Out', 'U', '4', 'F', 'F', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Centaur Outrider', 'C', '4', 'F', 'F', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cloud of Ash', 'U', '4', 'F', 'F', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Furnace Mage', 'U', '4', 'F', 'FF', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Guerrilla Fighter', 'C', '4', 'F', 'F', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Magma Javelin', 'C', '4', 'F', 'F', 'attachment', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Morningstar', 'U', '4', 'F', 'F', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Outlands Sniper', 'U', '4', 'F', 'FF', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rebel Illuminator', 'U', '4', 'F', 'F', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Recogulator', 'C', '4', 'F', 'F', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Steelfang Chakram', 'R', '4', 'F', 'F', 'attachment', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Blazing Renegade', 'C', '5', 'F', 'F', 'unit', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Calderan Gunsmith', 'U', '5', 'F', 'F', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cenatur Raidleader', 'U', '5', 'F', 'FF', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dusthoof Brawler', 'C', '5', 'F', 'F', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Infernus', 'R', '5', 'F', 'F', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Oblitarate', 'R', '5', 'F', 'FF', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Shogun of the Wastes', 'L', '5', 'F', 'FF', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Soulfire Drake', 'L', '5', 'F', 'FF', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crowd Favorite', 'U', '6', 'F', 'F', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Frontline Cyclops', 'U', '6', 'F', 'F', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('General Izalio', 'R', '6', 'F', 'FF', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hellfire Rifle', 'U', '6', 'F', 'FF', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stonescar Maul', 'U', '6', 'F', 'FF', 'attachment', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Worldpyre Phoenix', 'R', '6', 'F', 'FF', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Claw of the First Dragon', 'L', '7', 'F', 'FF', 'attachment', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Steelbound Dragon', 'R', '7', 'F', 'FF', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Kaleb, Uncrowned Prince', 'L', '8', 'F', 'FFF', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lavablood Goliath', 'L', '9', 'F', 'FF', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Amber Monument', 'U', 'N', 'T', 'T', 'power', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Copper Conduit', 'R', '0', 'T', 'T', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sand Warrior', 'U', '0', 'T', 'TTT', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Excavate', 'U', '1', 'T', 'T', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Humbug', 'C', '1', 'T', 'T', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Infinite Hourglass', 'U', '1', 'T', 'T', 'attachment', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Initiate of the Sands', 'C', '1', 'T', 'T', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ornamental Daggers', 'C', '1', 'T', 'T', 'attachment', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Predator’s Instinct', 'C', '1', 'T', 'T', 'spell', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sanctuary Priest', 'C', '1', 'T', 'T', 'unit', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Slow', 'U', '1', 'T', 'T', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Water of Life', 'C', '1', 'T', 'T', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Accelerate', 'C', '2', 'T', 'T', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Bold Adventurer', 'C', '2', 'T', 'T', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ephemeral Whisp', 'R', '2', 'T', 'T', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Friendly Whisp', 'U', '2', 'T', 'T', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Refresh', 'C', '2', 'T', 'T', 'spell', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Saurapod Wrangler', 'C', '2', 'T', 'T', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Synchronized Strike', 'C', '2', 'T', 'T', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Teleport', 'C', '2', 'T', 'T', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Voice of the Speaker', 'R', '2', 'T', 'T', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ageless Mentor', 'U', '3', 'T', 'T', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Amber Acolyte', 'C', '3', 'T', 'T', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Clockroach', 'R', '3', 'T', 'TT', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dawnwalker', 'R', '3', 'T', 'TT', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Decay', 'C', '3', 'T', 'T', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Determined Stranger', 'U', '3', 'T', 'T', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dispel', 'C', '3', 'T', 'T', 'spell', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dune Phantom', 'U', '3', 'T', 'T', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scorpion Wasp', 'U', '3', 'T', 'T', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Secret Pages', 'U', '3', 'T', 'T', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Unlock Potential', 'U', '3', 'T', 'T', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ancient Lore', 'U', '4', 'T', 'TT', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Healer’s Cloak', 'U', '4', 'T', 'T', 'attachment', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Horned Vorlunk', 'C', '4', 'T', 'T', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Marisen’s Disciple', 'R', '4', 'T', 'T', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Praxis Displacer', 'U', '4', 'T', 'TT', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sandstorm Titan', 'L', '4', 'T', 'TT', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Steward of Prophesy', 'R', '4', 'T', 'T', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Towertop Patrol', 'C', '4', 'T', 'T', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Vault of the Praxis', 'R', '4', 'T', 'TT', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Xenan Guardian', 'C', '4', 'T', 'T', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Xenan Obelisk', 'R', '4', 'T', 'T', 'attachment', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Elysian Pathfinder', 'U', '5', 'T', 'T', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Idol of Destran', 'L', '5', 'T', 'TT', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lumen Defender', 'U', '5', 'T', 'T', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Reliquary Raider', 'R', '5', 'T', 'T', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Striking Snake Formation', 'R', '5', 'T', 'TT', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Towering Terrazon', 'C', '5', 'T', 'TT', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Twinbrood Sauropod', 'U', '5', 'T', 'TT', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Divining Rod', 'R', '6', 'T', 'T', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lumen Shepherd', 'U', '6', 'T', 'T', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Mystic Ascendant', 'L', '6', 'T', 'T', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Predatory Carnosaur', 'R', '6', 'T', 'TTT', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ancient Terrazon', 'L', '7', 'T', 'TTT', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dormant Sentinel', 'C', '7', 'T', 'TT', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hall of Lost Kings', 'R', '7', 'T', 'TT', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Pillar of Amar', 'U', '7', 'T', 'TTT', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Marisen, the Eldest', 'L', '8', 'T', 'TT', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Talir, Who Sees Beyond', 'L', '8', 'T', 'TTT', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Emerald Monument', 'U', 'N', 'J', 'J', 'power', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Detain', 'C', '1', 'J', 'J', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('District Infantry', 'C', '1', 'J', 'J', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Elder’s Feather', 'U', '1', 'J', 'J', 'attachment', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Finest Hour', 'C', '1', 'J', 'J', 'spell', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Inspire', 'C', '1', 'J', 'J', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Protect', 'U', '1', 'J', 'J', 'spell', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Tinker Apprentice', 'U', '1', 'J', 'J', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Valkyrie Aspirant', 'C', '1', 'J', 'J', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Argenport Soldier', 'C', '2', 'J', 'J', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crownwatch Longsword', 'C', '2', 'J', 'J', 'attachment', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crownwatch Palading', 'U', '2', 'J', 'J', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Eager Owlet', 'R', '2', 'J', 'J', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Minotaur Grunt', 'C', '2', 'J', 'J', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Palading Oathbook', 'R', '2', 'J', 'J', 'attachment', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rebuke', 'C', '2', 'J', 'J', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Reinforce', 'C', '2', 'J', 'J', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Tinker Overseer', 'R', '2', 'J', 'J', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Vanquish', 'U', '2', 'J', 'J', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Auric Centry', 'U', '3', 'J', 'J', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Brightmace Paladin', 'C', '3', 'J', 'J', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Emerald Acolyte', 'C', '3', 'J', 'J', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Gilded Glaive', 'U', '3', 'J', 'JJ', 'attachment', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hero of the People', 'U', '3', 'J', 'J', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hooru Envoy', 'R', '3', 'J', 'JJ', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Loyal Watchwing', 'C', '3', 'J', 'J', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Mark of Shame', 'U', '3', 'J', 'J', 'attachment', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Order of the Spire', 'R', '3', 'J', 'J', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Privilege of Rank', 'U', '3', 'J', 'J', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Silverwing Familiar', 'U', '3', 'J', 'J', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Spire Chaplain', 'R', '3', 'J', 'J', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Valkyrie Enforcer', 'R', '3', 'J', 'JJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Valorous Stranger', 'U', '3', 'J', 'J', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Armorsmith', 'U', '4', 'J', 'J', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Auric Runehammer', 'R', '4', 'J', 'JJ', 'attachment', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Bronze Cuirass', 'U', '4', 'J', 'J', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Copperhall Blessing', 'R', '4', 'J', 'J', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Copperhall Recruit', 'C', '4', 'J', 'J', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crownwatch Cavalry', 'U', '4', 'J', 'J', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hammer of Might', 'R', '4', 'J', 'J', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Silverwing Avenger', 'U', '4', 'J', 'JJ', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stalwart Shield', 'C', '4', 'J', 'J', 'attachment', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Treasury Gate', 'L', '4', 'J', 'J', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Combrei Magister', 'U', '5', 'J', 'J', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Harsh Rule', 'R', '5', 'J', 'JJ', 'spell', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hooru Fledgling', 'C', '5', 'J', 'J', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Marshal Ironthorn', 'L', '5', 'J', 'JJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Mithril Mace', 'C', '5', 'J', 'JJ', 'attachment', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Silverwing Commander', 'R', '5', 'J', 'JJ', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Augmented Form', 'L', '6', 'J', 'JJJ', 'spell', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ceremonial Mask', 'U', '6', 'J', 'JJ', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Civic Peacekeeper', 'C', '6', 'J', 'J', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Fourth-Tree Elder', 'U', '6', 'J', 'JJ', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Plated Demolisher', 'L', '6', 'J', 'JJ', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Valkyrie Wings', 'R', '6', 'J', 'JJ', 'attachment', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Flight Lieutenant', 'U', '7', 'J', 'J', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rolant’s Honor Guard', 'R', '7', 'J', 'JJ', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rolant, the Iron Fist', 'L', '8', 'J', 'JJJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sword of the Sky King', 'L', '8', 'J', 'JJ', 'attachment', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cobalt Monument', 'U', 'N', 'P', 'P', 'power', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Blind Storyteller', 'U', '1', 'P', 'P', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Levitate', 'C', '1', 'P', 'P', 'spell', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Permafrost', 'U', '1', 'P', 'P', 'attachment', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Unstable Form', 'U', '1', 'P', 'P', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Yeti Spy', 'C', '1', 'P', 'P', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Backlash', 'C', '2', 'P', 'P', 'spell', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cloudsnake Saddle', 'R', '2', 'P', 'P', 'attachment', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('East-Wind Herald', 'C', '2', 'P', 'P', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Herald’s Song', 'C', '2', 'P', 'P', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lightning Storm', 'U', '2', 'P', 'P', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lightning Strike', 'C', '2', 'P', 'P', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Second Sight', 'C', '2', 'P', 'P', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Static Bolt', 'C', '2', 'P', 'P', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Tundra Explorer', 'U', '2', 'P', 'P', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Violent Gust', 'C', '2', 'P', 'P', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Whispering Wind', 'R', '2', 'P', 'P', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Wild Cloudsnake', 'U', '2', 'P', 'P', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Yeti Snowslinger', 'C', '2', 'P', 'P', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cobalt Acolyte', 'C', '3', 'P', 'P', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Eye of Winter', 'R', '3', 'P', 'P', 'attachment', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Flash Freeze', 'C', '3', 'P', 'P', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ice Sprite', 'U', '3', 'P', 'P', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Icebreaker', 'U', '3', 'P', 'P', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Mirror Image', 'U', '3', 'P', 'P', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Polymorph', 'U', '3', 'P', 'P', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scaly Gruan', 'C', '3', 'P', 'P', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Skysnapper', 'C', '3', 'P', 'P', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Wisdom of the Elders', 'C', '3', 'P', 'PP', 'spell', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Deranged Dinomancer', 'R', '4', 'P', 'PP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Jarrall’s Frostkin', 'C', '4', 'P', 'P', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rain of Frogs', 'R', '4', 'P', 'P', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Serpent Trainer', 'C', '4', 'P', 'P', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Soaring Stranger', 'U', '4', 'P', 'P', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stormcaller', 'U', '4', 'P', 'PP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Yeti Troublemaker', 'U', '4', 'P', 'P', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Aerial Ace', 'C', '5', 'P', 'P', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crystallize', 'R', '5', 'P', 'PP', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Elysian Trailblazer', 'U', '5', 'P', 'P', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Jotun Hurler', 'U', '5', 'P', 'P', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Jotun Warrior', 'C', '5', 'P', 'P', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Magus of the Mist', 'L', '5', 'P', 'PPP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Psionic Savant', 'U', '5', 'P', 'P', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Skycrag Wyvarch', 'U', '5', 'P', 'PP', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Staff of Stories', 'R', '5', 'P', 'PP', 'attachment', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('West-Wind Herald', 'R', '5', 'P', 'PP', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Windshaper', 'U', '5', 'P', 'P', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Celestial Omen', 'R', '6', 'P', 'PP', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hatchery Hunter', 'R', '6', 'P', 'PPP', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Jarrall Icerheart', 'L', '6', 'P', 'PPP', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('North-Wind Herald', 'U', '6', 'P', 'PP', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sapphire Dragon', 'U', '6', 'P', 'PP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scouting Party', 'R', '6', 'P', 'P', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Thunderstrike Dragon', 'R', '6', 'P', 'PPP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Araktodon', 'C', '7', 'P', 'P', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Mistveil Drake', 'R', '7', 'P', 'P', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rimescale Draconus', 'L', '7', 'P', 'PP', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Strength of the Pack', 'L', '7', 'P', 'PPP', 'spell', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Channel the Tempest', 'R', '8', 'P', 'PPPP', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Eilyn, Queen of the Wilds', 'L', '8', 'P', 'PPP', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scourge of Frosthome', 'L', '8', 'P', 'PPP', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Amethyst Monument', 'U', 'N', 'S', 'S', 'power', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Blood Beetle', 'C', '1', 'S', 'S', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dark Return', 'C', '1', 'S', 'S', 'spell', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Direfang Spider', 'C', '1', 'S', 'S', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ghostform', 'U', '1', 'S', 'S', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Knifejack', 'U', '1', 'S', 'S', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Pilfer', 'C', '1', 'S', 'S', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rapid Shot', 'C', '1', 'S', 'S', 'spell', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sabotage', 'C', '1', 'S', 'S', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Slumbering Stone', 'U', '1', 'S', 'S', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Suffocate', 'U', '1', 'S', 'S', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Annihilate', 'U', '2', 'S', 'S', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Argenport Instigator', 'R', '2', 'S', 'S', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cabal Cutthroat', 'U', '2', 'S', 'S', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Dark Wisp', 'C', '2', 'S', 'S', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Devour', 'C', '2', 'S', 'S', 'spell', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lethrai Ranger', 'C', '2', 'S', 'S', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scavenging Vulture', 'C', '2', 'S', 'S', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sporefolk', 'U', '2', 'S', 'S', 'unit', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Venomfang Dagger', 'C', '2', 'S', 'S', 'attachment', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Amethyst Acolyte', 'C', '3', 'S', 'S', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Beastcaller’s Amulet', 'U', '3', 'S', 'S', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Blackguard Sidearm', 'C', '3', 'S', 'S', 'attachment', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cabal Countess', 'R', '3', 'S', 'SS', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Desperado', 'U', '3', 'S', 'SS', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Direwood Beastcaller', 'R', '3', 'S', 'S', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Execute', 'C', '3', 'S', 'S', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lethrai Nightblade', 'U', '3', 'S', 'S', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lifedrinker', 'U', '3', 'S', 'S', 'attachment', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Madness', 'U', '3', 'S', 'S', 'spell', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Plague', 'U', '3', 'S', 'S', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ravenous Thornbeast', 'C', '3', 'S', 'S', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scheme', 'C', '3', 'S', 'S', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Shadowlands Guide', 'R', '3', 'S', 'S', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Torrent of Spiders', 'U', '3', 'S', 'S', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Xenan Destroyer', 'C', '3', 'S', 'S', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Back-Alley Bouncer', 'C', '4', 'S', 'S', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cabal Recruiter', 'U', '4', 'S', 'S', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Deathstrike', 'U', '4', 'S', 'S', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Impending Doom', 'R', '4', 'S', 'SS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lethrai Falchion', 'R', '4', 'S', 'SS', 'attachment', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Soul Collector', 'U', '4', 'S', 'SS', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Steward of the Past', 'R', '4', 'S', 'S', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stonescar Magus', 'C', '4', 'S', 'S', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Subvert', 'U', '4', 'S', 'S', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ashara, the Deadshot', 'R', '5', 'S', 'SS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Grasping at Shadows', 'R', '5', 'S', 'SS', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Lurking Sanguar', 'R', '5', 'S', 'S', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Merciless Stranger', 'U', '5', 'S', 'S', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Oblivion Spike', 'R', '5', 'S', 'SS', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Umbren Reaper', 'R', '5', 'S', 'SS', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Argenport Ringmaster', 'R', '6', 'S', 'SS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Direwood Rampager', 'C', '6', 'S', 'S', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Horsesnatcher Bat', 'U', '6', 'S', 'SS', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Spirit Drain', 'C', '6', 'S', 'SS', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Whispers in the Void', 'L', '6', 'S', 'SSSS', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Azindel’s Gift', 'R', '7', 'S', 'S', 'attachment', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Venomspine Hydra', 'L', '7', 'S', 'SS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Touch of the Ambren', 'L', '8', 'S', 'SS', 'attachment', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Vara, Fate-Touched', 'L', '8', 'S', 'SSS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('The Last Word', 'L', '8', 'S', 'SSS', 'attachment', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('The Witching Hour', 'L', '8', 'S', 'SSS', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rakano Banner', 'C', 'N', 'FJ', 'FJ', 'power', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Fearless Nomad', 'R', '1', 'FJ', 'FJ', 'unit', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Champion of Glory', 'R', '2', 'FJ', 'FJ', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rakano Artisan', 'R', '2', 'FJ', 'FJ', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crownwatch Deserter', 'C', '3', 'FJ', 'FJ', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ijin, Imperial Armorer', 'L', '3', 'FJ', 'FFJ', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Sword of Icaria', 'U', '3', 'FJ', 'FJ', 'attachment', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Battlebur Centaur', 'U', '4', 'FJ', 'FJ', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Longhorn Sergeant', 'U', '4', 'FJ', 'FJ', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Navani, Warsinger', 'L', '4', 'FJ', 'FJ', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Renegade Valkyrie', 'C', '4', 'FJ', 'FJ', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Righteous Fury', 'R', '4', 'FJ', 'FJ', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Rise to the Challenge', 'R', '4', 'FJ', 'FJ', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Deepforged Plate', 'L', '5', 'FJ', 'FFJJ', 'attachment', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Field Captain', 'U', '5', 'FJ', 'FJ', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Ferocious Stranger', 'R', '5', 'FJ', 'FJ', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Startsteel Daisho', 'L', '6', 'FJ', 'FFJJ', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Icaria, the Liberator', 'L', '7', 'FJ', 'FFFJJJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Combrei Banner', 'C', 'N', 'TJ', 'TJ', 'power', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Safe Return', 'C', '1', 'TJ', 'TJ', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Awakened Student', 'C', '2', 'TJ', 'TJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Desert Marshal', 'U', '2', 'TJ', 'TJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Combrei Healer', 'U', '3', 'TJ', 'TJ', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Knight-Chancellor Siraf', 'L', '3', 'TJ', 'TJ', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stand Together', 'R', '3', 'TJ', 'TJ', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Vodakhan’s Staff', 'R', '3', 'TJ', 'TJ', 'attachment', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Copperhall Elite', 'R', '4', 'TJ', 'TJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Elightened Stranger', 'R', '4', 'TJ', 'TJ', 'unit', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Karmic Guardian', 'U', '4', 'TJ', 'TTJ', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('The Great Parliament', 'L', '4', 'TJ', 'TJ', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Reality Warden', 'L', '5', 'TJ', 'TTJJ', 'spell', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stronghold’s Visage', 'R', '5', 'TJ', 'TJ', 'attachment', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Champion of Progress', 'R', '6', 'TJ', 'TJ', 'unit', '16');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Minotaur Ambassador', 'U', '6', 'TJ', 'TJ', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Vodakhan, Temple Speaker', 'L', '7', 'TJ', 'TTTJJJ', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('A New Tomorrow', 'L', '10', 'TJ', 'TJ', 'spell', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Elysian Banner', 'C', 'N', 'TP', 'TP', 'power', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Call the Ancients', 'L', '1', 'TP', 'TP', 'spell', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Accelerated Evolution', 'R', '2', 'TP', 'TP', 'spell', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Storm Lynx', 'U', '2', 'TP', 'TP', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Twinning Ritual', 'U', '2', 'TP', 'TP', 'spell', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Amaran Camel', 'C', '2', 'TP', 'TP', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crown of Possibilities', 'L', '3', 'TP', 'TP', 'attachment', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('False Prince', 'U', '3', 'TP', 'TTP', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Pteriax Hatchling', 'C', '3', 'TP', 'TP', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Champion of Wisdom', 'R', '4', 'TP', 'TP', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Crystalline Chalice', 'R', '4', 'TP', 'TPP', 'attachment', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Nesting Avisaur', 'U', '4', 'TP', 'TP', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Cirso, the Great Glutton', 'L', '5', 'TP', 'TTPP', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Explorer Emeritus', 'R', '5', 'TP', 'TTPP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hunting Pteriax', 'R', '5', 'TP', 'TP', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Fortunate Stranger', 'R', '6', 'TP', 'TP', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Curiox, the Collector', 'L', '7', 'TP', 'TTTPPP', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Shimmerpack', 'L', '8', 'TP', 'TTPP', 'spell', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Feln Banner', 'C', 'N', 'PS', 'PS', 'power', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Twilight Raptor', 'U', '1', 'PS', 'PS', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Gorgon Swiftblade', 'C', '2', 'PS', 'PS', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Grim Stranger', 'R', '2', 'PS', 'PS', 'unit', '13');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Haunting Scream', 'U', '2', 'PS', 'PS', 'spell', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Feln Bloodcaster', 'R', '3', 'PS', 'PSS', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Feln Cauldron', 'L', '3', 'PS', 'PS', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Gorgon Fanatic', 'U', '3', 'PS', 'PS', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Midnight Gale', 'L', '3', 'PS', 'PPSS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Recurring Nightmare', 'R', '3', 'PS', 'PS', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Trickster’s Cloak', 'C', '3', 'PS', 'PS', 'attachment', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Feeding Time', 'U', '4', 'PS', 'PS', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Champion of Cunning', 'R', '5', 'PS', 'PS', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Spell Swipe', 'R', '5', 'PS', 'PS', 'spell', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Withering Witch', 'R', '5', 'PS', 'PS', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Black-Sky Harbinger', 'L', '6', 'PS', 'PS', 'unit', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Nightmaw, Sight Unseen', 'L', '7', 'PS', 'PPPSSS', 'unit', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Snowcrush Animist', 'L', '7', 'PS', 'PPSS', 'unit', '40');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stonescar Banner', 'C', 'N', 'FS', 'FS', 'power', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Combust', 'C', '1', 'FS', 'FS', 'spell', '20');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Hair-Trigger Stranger', 'R', '2', 'FS', 'FS', 'unit', '3');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Obsidian Golem', 'C', '2', 'FS', 'FS', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Treachery', 'U', '2', 'FS', 'FS', 'spell', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Bloodrite Kalis', 'R', '3', 'FS', 'FS', 'attachment', '25');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Brimstone Altar', 'R', '3', 'FS', 'FS', 'attachment', '7');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Champion of Chaos', 'R', '3', 'FS', 'FS', 'unit', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Bandit Queen', 'L', '4', 'FS', 'FFS', 'unit', '35');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Black Iron Manacles', 'R', '4', 'FS', 'FS', 'attachment', '1');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Statuary MAiden', 'L', '4', 'FS', 'FS', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Runic Revolver', 'U', '5', 'FS', 'FS', 'attachment', '30');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Scraptank', 'L', '5', 'FS', 'FS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Smuggler’s Stash', 'U', '5', 'FS', 'FS', 'spell', '50');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Warband Chieftain', 'U', '5', 'FS', 'FS', 'unit', '45');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Infernal Tyrant', 'R', '6', 'FS', 'FFSS', 'unit', '60');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Stonescar Leviathan', 'L', '7', 'FS', 'FFSS', 'unit', '10');
INSERT INTO TET (name, rarity, cost, faction, infreq, card_type, RNG) VALUES ('Voprex, the Great Ruin', 'L', '7', 'FS', 'FFFSSS', 'unit', '20');